version: "3.9"
services:
# deCONZ
  deconz:
    image: deconzcommunity/deconz:latest
    ports:
      - 9102:9102
      - 9143:9143
    environment:
      - DECONZ_WS_PORT=9143
      - DECONZ_WEB_PORT=9102
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/deCONZ:/opt/deCONZ
    restart: always
# Portainer agent vers le Portainer NAS
  portainer_agent:
    image: portainer/agent:latest
    privileged: true    
    ports:
      - 9001:9001
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    restart: always