version: "3.9"
services:
# deCONZ
  deconz:
    image: deconzcommunity/deconz:latest
    ports:
      - 9102:9102
      - 9143:9143
    environment:
      - DECONZ_WS_PORT=9143
      - DECONZ_WEB_PORT=9102
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/deCONZ:/opt/deCONZ
    restart: always
