version: "3.2"
services:
# CAPTEUR DHT11
#  dht11:
#    image: vzwingmann/wiringpi:arm-dht11
#    environment:
#      - APP_NAME=DHT11
#    ports:
#      - 9100:9100
#    devices:
#      - /dev/ttyAMA0:/dev/ttyAMA0
#      - /dev/mem:/dev/mem
#    privileged: true
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    restart: always
# CAPTEUR RADIO
#  radio:
#    image: vzwingmann/wiringpi:arm-radio
#    environment:
#      - APP_NAME=Radio
#    ports:
#      - 9101:9100
#    devices:
#      - /dev/ttyAMA0:/dev/ttyAMA0
#      - /dev/mem:/dev/mem
#    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    privileged: true
#    restart: always
# TYDOM
  tydom-bridge:
    image: vzwingmadomatic/domoticz-tydom:latest
    environment:
      - PORT=9101
      - HOST=192.168.1.13
      - MAC= #Set Tydom MAC Adress
      - PASSWD= #Set Tydom Password
    ports:
      - 9101:9101
    restart: always
# DOMOTICZ
  domoticz:
    image: vzwingmadomatic/domoticz:latest
    environment:
      - TZ=Europe/Paris
      - LD_LIBRARY_PATH=/opt/vc/lib/
    ports:
      - 8080:8080
      - 8443:443
    volumes:
      - /opt/vc/:/opt/vc/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/domoticz/database:/opt/domoticz/userdata
      - /home/pi/appli/domoticz/scripts/dzVents:/opt/domoticz/userdata/scripts/dzVents/generated_scripts
    depends_on:
#      - dht11
#      - radio
      - tydom-bridge
    restart: always