version: "3.2"
services:
# TYDOM
  tydom-bridge:
    image: vzwingmadomatic/domoticz-tydom:latest
    environment:
      # Configuration Box Tydom
      - HOST=tydom.local
      # Configuration passerelle Tydom
      - PORT=9001
      - MAC=#Set TYDOM MAC adress
      - PASSWD=#Set TYDOM password
    ports:
      - 9101:9001
    restart: always
# deCONZ
  deconz:
    image: marthoc/deconz:latest
    ports:
      - 9102:9102
      - 9143:9143
    environment:
      - DECONZ_WS_PORT=9143
      - DECONZ_WEB_PORT=9102
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro    
      - /home/pi/appli/deCONZ:/root/.local/share/dresden-elektronik/deCONZ/
    restart: always
# DOMOTICZ
  domoticz:
    image: vzwingmadomatic/domoticz:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - 8080:8080
      - 8443:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/domoticz/database/domoticz.db:/opt/domoticz/userdata/domoticz.db
#      - /home/pi/appli/domoticz/scripts/dzVents:/opt/domoticz/userdata/scripts/dzVents/generated_scripts
    depends_on:
      - deconz
      - tydom-bridge
    restart: always