version: "3.2"
services:
# TYDOM
  tydom-bridge:
    image: vzwingmadomatic/domoticz-tydom:latest
    environment:
      # Configuration Box Tydom
      # - HOST=192.168.1.13
      # Configuration passerelle Tydom
      - PORT=9001
      - MAC=#Set Tydom MAC Adresse
      - PASSWD=#Set Tydom Password
    ports:
      - 9101:9001
    restart: always
# deCONZ
  deconz:
    image: marthoc/deconz:latest
    ports:
      - 9102:80
      - 9143:443      
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro    
      - /home/pi/appli/deCONZ:/root/.local/share/dresden-elektronik/deCONZ/
    restart: always
# DOMOTICZ
  domoticz:
    image: vzwingmadomatic/domoticz:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - 8080:8080
      - 8443:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/domoticz/database:/opt/domoticz/userdata
      - /home/pi/appli/domoticz/scripts/dzVents:/opt/domoticz/userdata/scripts/dzVents/generated_scripts
    depends_on:
      - deconz
      - tydom-bridge
    restart: always