version: "3.9"
services:
# HTTPD
  httpd-proxy:
    image: vzwingmadomatic/httpd:latest
    ports:
      - 8243:8243  
      - 8280:8280      
    volumes:
      - /home/pi/appli/httpd_logs:/usr/local/apache2/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
# TYDOM
  tydom-bridge:
    image: vzwingmadomatic/domoticz-tydom:latest
    environment:
      # Configuration Box Tydom
      - HOST=tydom.local
      - MAC=#Set TYDOM MAC adress
      - PASSWD=#Set TYDOM password      
      # Configuration passerelle Tydom
      - PORT=9001
      # Configuration pour les api
      - AUTHAPI=#Set Auth login for API
      - PASSWDAPI=#Set Auth password for API
    ports:
      - 9101:9001
    restart: always
# deCONZ
  deconz:
    image: deconzcommunity/deconz:latest
    ports:
      - 9102:9102
      - 9143:9143
    environment:
      - DECONZ_WS_PORT=9143
      - DECONZ_WEB_PORT=9102
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/deCONZ:/opt/deCONZ
    restart: always
# DOMOTICZ
  domoticz:
    image: vzwingmadomatic/domoticz:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - 8080:8080
      - 8443:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/appli/domoticz/database/domoticz.db:/opt/domoticz/userdata/domoticz.db
#      - /home/pi/appli/domoticz/scripts/dzVents:/opt/domoticz/userdata/scripts/dzVents/generated_scripts
    depends_on:
      - deconz
      - tydom-bridge
    restart: always
# Watcher des images utilisées dans ce fichier pour auto-update
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock